version: "3"

services:
  api:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - "./sample_model:/models/sample_model"
    environment:
      - MODEL_NAME=sample_model
    tty: true
    stdin_open: true
